export const ADD_PRODUCT_BEGIN = "ADD_PRODUCT_BEGIN";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";
export const UPDATE_PRODUCT_BEGIN = "UPDATE_PRODUCT_BEGIN";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";
export const REMOVE_PRODUCT_BEGIN = "REMOVE_PRODUCT_BEGIN";
export const REMOVE_PRODUCT_SUCESS = "REMOVE_PRODUCT_SUCESS";
export const REMOVE_PRODUCT_ERROR = "REMOVE_PRODUCT_ERROR";

export const FETCH_PRODUCTS_BEGIN = "FETCH_PRODUCTS_BEGIN";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";
export const PRODUCTS = "products";
export const SET_CURRENT_PRODUCT_TO_VIEW = "SET_CURRENT_PRODUCT_TO_VIEW";
export const SET_CURRENT_PRODUCT_TO_EDIT = "SET_CURRENT_PRODUCT_TO_EDIT";
