export const ADD_CATEGORY_BEGIN = "ADD_CATEGORY_BEGIN";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_ERROR = "ADD_CATEGORY_ERROR";

export const REMOVE_CATEGORY_BEGIN = "REMOVE_CATEGORY_BEGIN";
export const REMOVE_CATEGORY_SUCESS = "REMOVE_CATEGORY_SUCESS";
export const REMOVE_CATEGORY_ERROR = "REMOVE_CATEGORY_ERROR";

export const FETCH_CATEGORIES_BEGIN = "FETCH_CATEGORIES_BEGIN";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_ERROR = "FETCH_CATEGORIES_ERROR";
export const CATEGORIES = "categories";
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";
